// Code generated by qtc from "admin.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/admin.qtpl:1
package views

//line views/admin.qtpl:1
import "github.com/bouncepaw/mycorrhiza/user"

//line views/admin.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/admin.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/admin.qtpl:3
func StreamAdminUsersPanelHTML(qw422016 *qt422016.Writer, userList []*user.User) {
//line views/admin.qtpl:3
	qw422016.N().S(`
<div class="layout">
<main class="main-width">
	<h1>Manage users</h1>

	<form action="/admin/reindex-users" method="get">
		<button class="btn btn_accent" type="submit">Reindex users</button>
	</form>

	<h2>Users list</h2>

	<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Group</th>
			<th>Registered at</th>
		</tr>
	</thead>
	<tbody>
	`)
//line views/admin.qtpl:23
	for _, u := range userList {
//line views/admin.qtpl:23
		qw422016.N().S(`
		<tr>
			<td>`)
//line views/admin.qtpl:25
		qw422016.N().S(u.Name)
//line views/admin.qtpl:25
		qw422016.N().S(`</td>
			<td>`)
//line views/admin.qtpl:26
		qw422016.N().S(u.Group)
//line views/admin.qtpl:26
		qw422016.N().S(`</td>
			<td>`)
//line views/admin.qtpl:27
		qw422016.N().S(u.RegisteredAt.Format("2006-01-02 15:04:05-0700"))
//line views/admin.qtpl:27
		qw422016.N().S(`</td>
		</tr>
	`)
//line views/admin.qtpl:29
	}
//line views/admin.qtpl:29
	qw422016.N().S(`
	</tbody>
	</table>
</main>
</div>
`)
//line views/admin.qtpl:34
}

//line views/admin.qtpl:34
func WriteAdminUsersPanelHTML(qq422016 qtio422016.Writer, userList []*user.User) {
//line views/admin.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/admin.qtpl:34
	StreamAdminUsersPanelHTML(qw422016, userList)
//line views/admin.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line views/admin.qtpl:34
}

//line views/admin.qtpl:34
func AdminUsersPanelHTML(userList []*user.User) string {
//line views/admin.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line views/admin.qtpl:34
	WriteAdminUsersPanelHTML(qb422016, userList)
//line views/admin.qtpl:34
	qs422016 := string(qb422016.B)
//line views/admin.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line views/admin.qtpl:34
	return qs422016
//line views/admin.qtpl:34
}
