// Code generated by qtc from "mutators.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/mutators.qtpl:1
package views

//line views/mutators.qtpl:1
import "net/http"

//line views/mutators.qtpl:2
import "github.com/bouncepaw/mycorrhiza/util"

//line views/mutators.qtpl:3
import "github.com/bouncepaw/mycorrhiza/user"

//line views/mutators.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/mutators.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/mutators.qtpl:5
func StreamToolbar(qw422016 *qt422016.Writer, u *user.User) {
//line views/mutators.qtpl:5
	qw422016.N().S(`
<aside class="edit-toolbar layout-card">
	<h2 class="edit-toolbar__title layout-card__title">Markup</h2>
	<section class="edit-toolbar__buttons">
	`)
//line views/mutators.qtpl:9
	for _, el := range []struct {
		class   string
		onclick string
		display string
	}{
		{"link", "wrapLink()", "[[link]]"},
		{"heading2", "insertHeading2()", "## heading"},
		{"heading3", "insertHeading3()", "### heading"},
		{"bold", "wrapBold()", "<b>**Bold**</b>"},
		{"italic", "wrapItalic()", "<i>//Italic//</i>"},
		{"highlighted", "wrapHighlighted()", "<mark>!!Highlight!!</mark>"},
		{"monospace", "wrapMonospace()", "<code>`Monospace`</code>"},
		{"lifted", "wrapLifted()", "<sup>^Lifted^</sup>"},
		{"lowered", "wrapLowered()", "<sub>,,Lowered,,</sub>"},
		{"strikethrough", "wrapStrikethrough()", "<strike>~~Strikethrough~~</strike>"},
		{"rocket", "insertRocket()", "=> rocketlink"},
		{"xcl", "insertXcl()", "<= transclusion"},
		{"img", "insertImgBlock()", "<code>img {}</code>"},
		{"table", "insertTableBlock()", "<code>table {}</code>"},
		{"hr", "insertHorizontalBar()", "Horizontal bar"},
		{"codeblock", "insertCodeblock()", "Code block"},
	} {
//line views/mutators.qtpl:30
		qw422016.N().S(`
		<button
			class="edit-toolbar__btn edit-toolbar__`)
//line views/mutators.qtpl:32
		qw422016.E().S(el.class)
//line views/mutators.qtpl:32
		qw422016.N().S(`"
			onclick="`)
//line views/mutators.qtpl:33
		qw422016.E().S(el.onclick)
//line views/mutators.qtpl:33
		qw422016.N().S(`">
			`)
//line views/mutators.qtpl:34
		qw422016.N().S(el.display)
//line views/mutators.qtpl:34
		qw422016.N().S(`
		</button>
	`)
//line views/mutators.qtpl:36
	}
//line views/mutators.qtpl:36
	qw422016.N().S(`
	</section>
	<p class="edit-toolbar__ad"><a href="https://mycorrhiza.lesarbr.es/hypha/mycomarkup">Learn more</a> about mycomarkup</p>
	<h2 class="edit-toolbar__title layout-card__title">Actions</h2>
	<section class="edit-toolbar__buttons">
	`)
//line views/mutators.qtpl:41
	for _, el := range []struct {
		class   string
		onclick string
		display string
	}{
		{"date", "insertDate()", "Insert current date"},
	} {
//line views/mutators.qtpl:47
		qw422016.N().S(`
		<button
			class="edit-toolbar__btn edit-toolbar__`)
//line views/mutators.qtpl:49
		qw422016.E().S(el.class)
//line views/mutators.qtpl:49
		qw422016.N().S(`"
			onclick="`)
//line views/mutators.qtpl:50
		qw422016.E().S(el.onclick)
//line views/mutators.qtpl:50
		qw422016.N().S(`">
			`)
//line views/mutators.qtpl:51
		qw422016.N().S(el.display)
//line views/mutators.qtpl:51
		qw422016.N().S(`
		</button>
	`)
//line views/mutators.qtpl:53
	}
//line views/mutators.qtpl:53
	qw422016.N().S(`
	`)
//line views/mutators.qtpl:54
	if u.Group != "anon" {
//line views/mutators.qtpl:54
		qw422016.N().S(`
		<button
			class="edit-toolbar__btn edit-toolbar__user-link"
			onclick="insertUserlink()">
			Link yourself
		</button>
	`)
//line views/mutators.qtpl:60
	}
//line views/mutators.qtpl:60
	qw422016.N().S(`
	</section>
</aside>
<script src="/static/toolbar.js"></script>
`)
//line views/mutators.qtpl:64
}

//line views/mutators.qtpl:64
func WriteToolbar(qq422016 qtio422016.Writer, u *user.User) {
//line views/mutators.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/mutators.qtpl:64
	StreamToolbar(qw422016, u)
//line views/mutators.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line views/mutators.qtpl:64
}

//line views/mutators.qtpl:64
func Toolbar(u *user.User) string {
//line views/mutators.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
//line views/mutators.qtpl:64
	WriteToolbar(qb422016, u)
//line views/mutators.qtpl:64
	qs422016 := string(qb422016.B)
//line views/mutators.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
//line views/mutators.qtpl:64
	return qs422016
//line views/mutators.qtpl:64
}

//line views/mutators.qtpl:66
func StreamEditHTML(qw422016 *qt422016.Writer, rq *http.Request, hyphaName, textAreaFill, warning string) {
//line views/mutators.qtpl:66
	qw422016.N().S(`
`)
//line views/mutators.qtpl:67
	qw422016.N().S(NavHTML(rq, hyphaName, "edit"))
//line views/mutators.qtpl:67
	qw422016.N().S(`
<div class="layout">
<main class="main-width edit edit_no-preview">
	<h1 class="edit__title">Edit `)
//line views/mutators.qtpl:70
	qw422016.E().S(util.BeautifulName(hyphaName))
//line views/mutators.qtpl:70
	qw422016.N().S(`</h1>
	`)
//line views/mutators.qtpl:71
	qw422016.N().S(warning)
//line views/mutators.qtpl:71
	qw422016.N().S(`
	<form method="post" class="edit-form"
			action="/upload-text/`)
//line views/mutators.qtpl:73
	qw422016.E().S(hyphaName)
//line views/mutators.qtpl:73
	qw422016.N().S(`">
		<textarea name="text" class="edit-form__textarea">`)
//line views/mutators.qtpl:74
	qw422016.E().S(textAreaFill)
//line views/mutators.qtpl:74
	qw422016.N().S(`</textarea>
		<br/>
		<input type="submit" name="action" value="Save" class="edit-form__save"/>
		<input type="submit" name="action" value="Preview" class="edit-form__preview">
		<a href="/page/`)
//line views/mutators.qtpl:78
	qw422016.E().S(hyphaName)
//line views/mutators.qtpl:78
	qw422016.N().S(`" class="edit-form__cancel">Cancel</a>
	</form>
</main>
`)
//line views/mutators.qtpl:81
	qw422016.N().S(Toolbar(user.FromRequest(rq)))
//line views/mutators.qtpl:81
	qw422016.N().S(`
</div>
`)
//line views/mutators.qtpl:83
}

//line views/mutators.qtpl:83
func WriteEditHTML(qq422016 qtio422016.Writer, rq *http.Request, hyphaName, textAreaFill, warning string) {
//line views/mutators.qtpl:83
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/mutators.qtpl:83
	StreamEditHTML(qw422016, rq, hyphaName, textAreaFill, warning)
//line views/mutators.qtpl:83
	qt422016.ReleaseWriter(qw422016)
//line views/mutators.qtpl:83
}

//line views/mutators.qtpl:83
func EditHTML(rq *http.Request, hyphaName, textAreaFill, warning string) string {
//line views/mutators.qtpl:83
	qb422016 := qt422016.AcquireByteBuffer()
//line views/mutators.qtpl:83
	WriteEditHTML(qb422016, rq, hyphaName, textAreaFill, warning)
//line views/mutators.qtpl:83
	qs422016 := string(qb422016.B)
//line views/mutators.qtpl:83
	qt422016.ReleaseByteBuffer(qb422016)
//line views/mutators.qtpl:83
	return qs422016
//line views/mutators.qtpl:83
}

//line views/mutators.qtpl:85
func StreamPreviewHTML(qw422016 *qt422016.Writer, rq *http.Request, hyphaName, textAreaFill, warning string, renderedPage string) {
//line views/mutators.qtpl:85
	qw422016.N().S(`
`)
//line views/mutators.qtpl:86
	qw422016.N().S(NavHTML(rq, hyphaName, "edit"))
//line views/mutators.qtpl:86
	qw422016.N().S(`
<div class="layout">
<main class="main-width edit edit_with-preview">
	<h1>Edit `)
//line views/mutators.qtpl:89
	qw422016.E().S(util.BeautifulName(hyphaName))
//line views/mutators.qtpl:89
	qw422016.N().S(` (preview)</h1>
	`)
//line views/mutators.qtpl:90
	qw422016.N().S(warning)
//line views/mutators.qtpl:90
	qw422016.N().S(`
	<form method="post" class="edit-form"
			action="/upload-text/`)
//line views/mutators.qtpl:92
	qw422016.E().S(hyphaName)
//line views/mutators.qtpl:92
	qw422016.N().S(`">
		<textarea class="edit-form__textarea" name="text">`)
//line views/mutators.qtpl:93
	qw422016.E().S(textAreaFill)
//line views/mutators.qtpl:93
	qw422016.N().S(`</textarea>
		<br/>
		<input type="submit" name="action" value="Save" class="edit-form__save"/>
		<input type="submit" name="action" value="Preview" class="edit-form__preview">
		<a href="/page/`)
//line views/mutators.qtpl:97
	qw422016.E().S(hyphaName)
//line views/mutators.qtpl:97
	qw422016.N().S(`" class="edit-form__cancel">Cancel</a>
	</form>
	<p class="warning">Note that the hypha is not saved yet. You can preview the changes ↓</p>
	<article class="edit__preview">`)
//line views/mutators.qtpl:100
	qw422016.N().S(renderedPage)
//line views/mutators.qtpl:100
	qw422016.N().S(`</article>
</main>
`)
//line views/mutators.qtpl:102
	qw422016.N().S(Toolbar(user.FromRequest(rq)))
//line views/mutators.qtpl:102
	qw422016.N().S(`
</div>
`)
//line views/mutators.qtpl:104
}

//line views/mutators.qtpl:104
func WritePreviewHTML(qq422016 qtio422016.Writer, rq *http.Request, hyphaName, textAreaFill, warning string, renderedPage string) {
//line views/mutators.qtpl:104
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/mutators.qtpl:104
	StreamPreviewHTML(qw422016, rq, hyphaName, textAreaFill, warning, renderedPage)
//line views/mutators.qtpl:104
	qt422016.ReleaseWriter(qw422016)
//line views/mutators.qtpl:104
}

//line views/mutators.qtpl:104
func PreviewHTML(rq *http.Request, hyphaName, textAreaFill, warning string, renderedPage string) string {
//line views/mutators.qtpl:104
	qb422016 := qt422016.AcquireByteBuffer()
//line views/mutators.qtpl:104
	WritePreviewHTML(qb422016, rq, hyphaName, textAreaFill, warning, renderedPage)
//line views/mutators.qtpl:104
	qs422016 := string(qb422016.B)
//line views/mutators.qtpl:104
	qt422016.ReleaseByteBuffer(qb422016)
//line views/mutators.qtpl:104
	return qs422016
//line views/mutators.qtpl:104
}
