// Code generated by qtc from "mutators.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/mutators.qtpl:1
package views

//line views/mutators.qtpl:1
import "fmt"

//line views/mutators.qtpl:2
import "net/http"

//line views/mutators.qtpl:4
import "github.com/bouncepaw/mycorrhiza/cfg"

//line views/mutators.qtpl:5
import "github.com/bouncepaw/mycorrhiza/l18n"

//line views/mutators.qtpl:6
import "github.com/bouncepaw/mycorrhiza/user"

//line views/mutators.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/mutators.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/mutators.qtpl:8
func StreamToolbar(qw422016 *qt422016.Writer, u *user.User, lc *l18n.Localizer) {
//line views/mutators.qtpl:8
	qw422016.N().S(`
<aside class="edit-toolbar markup-toolbar layout-card">
	<h2 class="edit-toolbar__title layout-card__title">`)
//line views/mutators.qtpl:10
	qw422016.E().S(lc.Get("edit.markup"))
//line views/mutators.qtpl:10
	qw422016.N().S(`</h2>
	<section class="edit-toolbar__buttons">
	`)
//line views/mutators.qtpl:12
	for _, el := range []struct {
		class   string
		display string
	}{
		{"link", fmt.Sprintf("[[%s]]", lc.Get("edit.link"))},
		{"titlelink", fmt.Sprintf("[[%s | %s]]", lc.Get("edit.link"), lc.Get("edit.link_title"))},
		{"heading1", fmt.Sprintf("= %s", lc.Get("edit.heading"))},
		{"heading2", fmt.Sprintf("== %s", lc.Get("edit.heading"))},
		{"bold", fmt.Sprintf("<b>**%s**</b>", lc.Get("edit.bold"))},
		{"italic", fmt.Sprintf("<i>//%s//</i>", lc.Get("edit.italic"))},
		{"highlighted", fmt.Sprintf("<mark>++%s++</mark>", lc.Get("edit.highlight"))},
		{"underline", fmt.Sprintf("<u>__%s__</u>", lc.Get("edit.underline"))},
		{"monospace", fmt.Sprintf("<code>`%s`</code>", lc.Get("edit.mono"))},
		{"lifted", fmt.Sprintf("<sup>^^%s^^</sup>", lc.Get("edit.super"))}, // inconsistent names: lifted, supertext. How cute ❤️
		{"lowered", fmt.Sprintf("<sub>,,%s,,</sub>", lc.Get("edit.sub"))},
		{"strikethrough", fmt.Sprintf("<strike>~~%s~~</strike>", lc.Get("edit.strike"))},
		{"rocket", "=> " + lc.Get("edit.rocket")},
		{"xcl", "<= " + lc.Get("edit.transclude")},
		{"img", "<code>img {}</code>"},
		{"table", "<code>table {}</code>"},
		{"hr", lc.Get("edit.hr")},
		{"codeblock", lc.Get("edit.code")},
		{"bulletedlist", "* " + lc.Get("edit.bullets")},
		{"numberedlist", "*. " + lc.Get("edit.numbers")},
	} {
//line views/mutators.qtpl:36
		qw422016.N().S(`
		<button class="btn edit-toolbar__btn edit-toolbar__`)
//line views/mutators.qtpl:37
		qw422016.E().S(el.class)
//line views/mutators.qtpl:37
		qw422016.N().S(`">
			`)
//line views/mutators.qtpl:38
		qw422016.N().S(el.display)
//line views/mutators.qtpl:38
		qw422016.N().S(`
		</button>
	`)
//line views/mutators.qtpl:40
	}
//line views/mutators.qtpl:40
	qw422016.N().S(`
	</section>
	<p class="edit-toolbar__ad">`)
//line views/mutators.qtpl:42
	qw422016.N().S(lc.Get("edit.help", &l18n.Replacements{"link": fmt.Sprintf("<a href=\"/help/en/mycomarkup\" target=\"_blank\" class=\"shy-link\">%s</a>", lc.Get("edit.help_link"))}))
//line views/mutators.qtpl:42
	qw422016.N().S(`</p>
</aside>
<aside class="edit-toolbar action-toolbar layout-card">
	<h2 class="edit-toolbar__title layout-card__title">`)
//line views/mutators.qtpl:45
	qw422016.E().S(lc.Get("edit.actions"))
//line views/mutators.qtpl:45
	qw422016.N().S(`</h2>
	<section class="edit-toolbar__buttons">
	`)
//line views/mutators.qtpl:47
	for _, el := range []struct {
		class   string
		display string
	}{
		{"date", lc.Get("edit.date")},
		{"time", lc.Get("edit.time")},
	} {
//line views/mutators.qtpl:53
		qw422016.N().S(`
		<button class="btn edit-toolbar__btn edit-toolbar__`)
//line views/mutators.qtpl:54
		qw422016.E().S(el.class)
//line views/mutators.qtpl:54
		qw422016.N().S(`">
			`)
//line views/mutators.qtpl:55
		qw422016.N().S(el.display)
//line views/mutators.qtpl:55
		qw422016.N().S(`
		</button>
	`)
//line views/mutators.qtpl:57
	}
//line views/mutators.qtpl:57
	qw422016.N().S(`
	`)
//line views/mutators.qtpl:58
	if u.Group != "anon" {
//line views/mutators.qtpl:58
		qw422016.N().S(`
		<button class="btn edit-toolbar__btn edit-toolbar__user-link">
			`)
//line views/mutators.qtpl:60
		qw422016.E().S(lc.Get("edit.selflink"))
//line views/mutators.qtpl:60
		qw422016.N().S(`
		</button>
	`)
//line views/mutators.qtpl:62
	}
//line views/mutators.qtpl:62
	qw422016.N().S(`
	</section>
</aside>
<script src="/static/toolbar.js"></script>
`)
//line views/mutators.qtpl:66
}

//line views/mutators.qtpl:66
func WriteToolbar(qq422016 qtio422016.Writer, u *user.User, lc *l18n.Localizer) {
//line views/mutators.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/mutators.qtpl:66
	StreamToolbar(qw422016, u, lc)
//line views/mutators.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line views/mutators.qtpl:66
}

//line views/mutators.qtpl:66
func Toolbar(u *user.User, lc *l18n.Localizer) string {
//line views/mutators.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line views/mutators.qtpl:66
	WriteToolbar(qb422016, u, lc)
//line views/mutators.qtpl:66
	qs422016 := string(qb422016.B)
//line views/mutators.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line views/mutators.qtpl:66
	return qs422016
//line views/mutators.qtpl:66
}

//line views/mutators.qtpl:68
func StreamEditor(qw422016 *qt422016.Writer, rq *http.Request, hyphaName, textAreaFill, warning string) {
//line views/mutators.qtpl:68
	qw422016.N().S(`
`)
//line views/mutators.qtpl:70
	lc := l18n.FromRequest(rq)

//line views/mutators.qtpl:71
	qw422016.N().S(`
<main class="main-width edit edit_no-preview">
	<form method="post" class="edit-form"
			action="/upload-text/`)
//line views/mutators.qtpl:74
	qw422016.E().S(hyphaName)
//line views/mutators.qtpl:74
	qw422016.N().S(`">
		<h1 class="edit__title">`)
//line views/mutators.qtpl:75
	qw422016.N().S(fmt.Sprintf(lc.Get("edit.title"), beautifulLink(hyphaName)))
//line views/mutators.qtpl:75
	qw422016.N().S(`</h1>
		`)
//line views/mutators.qtpl:76
	qw422016.N().S(warning)
//line views/mutators.qtpl:76
	qw422016.N().S(`
		<textarea name="text" class="edit-form__textarea" autofocus>`)
//line views/mutators.qtpl:77
	qw422016.E().S(textAreaFill)
//line views/mutators.qtpl:77
	qw422016.N().S(`</textarea>
		<p class="edit-form__message-zone">
			<input id="text" type="text" name="message" class="edit-form__message" placeholder="`)
//line views/mutators.qtpl:79
	qw422016.E().S(lc.Get("edit.tag"))
//line views/mutators.qtpl:79
	qw422016.N().S(`" aria-label="`)
//line views/mutators.qtpl:79
	qw422016.E().S(lc.Get("edit.tag"))
//line views/mutators.qtpl:79
	qw422016.N().S(`">
		</p>
		<p class="edit-form__buttons">
			<button type="submit" name="action" class="btn btn_accent edit-form__save" value="Save">`)
//line views/mutators.qtpl:82
	qw422016.E().S(lc.Get("edit.save"))
//line views/mutators.qtpl:82
	qw422016.N().S(`</button>
			<button type="submit" name="action" class="btn edit-form__preview" value="Preview">`)
//line views/mutators.qtpl:83
	qw422016.E().S(lc.Get("edit.preview"))
//line views/mutators.qtpl:83
	qw422016.N().S(`</button>
			<a href="/hypha/`)
//line views/mutators.qtpl:84
	qw422016.E().S(hyphaName)
//line views/mutators.qtpl:84
	qw422016.N().S(`" class="btn btn_weak">`)
//line views/mutators.qtpl:84
	qw422016.E().S(lc.Get("ui.cancel"))
//line views/mutators.qtpl:84
	qw422016.N().S(`</a>
		</p>
	</form>
</main>
`)
//line views/mutators.qtpl:88
	qw422016.N().S(Toolbar(user.FromRequest(rq), lc))
//line views/mutators.qtpl:88
	qw422016.N().S(`
`)
//line views/mutators.qtpl:89
	streameditScripts(qw422016)
//line views/mutators.qtpl:89
	qw422016.N().S(`
`)
//line views/mutators.qtpl:90
}

//line views/mutators.qtpl:90
func WriteEditor(qq422016 qtio422016.Writer, rq *http.Request, hyphaName, textAreaFill, warning string) {
//line views/mutators.qtpl:90
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/mutators.qtpl:90
	StreamEditor(qw422016, rq, hyphaName, textAreaFill, warning)
//line views/mutators.qtpl:90
	qt422016.ReleaseWriter(qw422016)
//line views/mutators.qtpl:90
}

//line views/mutators.qtpl:90
func Editor(rq *http.Request, hyphaName, textAreaFill, warning string) string {
//line views/mutators.qtpl:90
	qb422016 := qt422016.AcquireByteBuffer()
//line views/mutators.qtpl:90
	WriteEditor(qb422016, rq, hyphaName, textAreaFill, warning)
//line views/mutators.qtpl:90
	qs422016 := string(qb422016.B)
//line views/mutators.qtpl:90
	qt422016.ReleaseByteBuffer(qb422016)
//line views/mutators.qtpl:90
	return qs422016
//line views/mutators.qtpl:90
}

//line views/mutators.qtpl:92
func StreamPreview(qw422016 *qt422016.Writer, rq *http.Request, hyphaName, textAreaFill, message, warning string, renderedPage string) {
//line views/mutators.qtpl:92
	qw422016.N().S(`
`)
//line views/mutators.qtpl:94
	lc := l18n.FromRequest(rq)

//line views/mutators.qtpl:95
	qw422016.N().S(`
<main class="main-width edit edit_with-preview">
	<form method="post" class="edit-form"
			action="/upload-text/`)
//line views/mutators.qtpl:98
	qw422016.E().S(hyphaName)
//line views/mutators.qtpl:98
	qw422016.N().S(`">
		<h1 class="edit__title">`)
//line views/mutators.qtpl:99
	qw422016.N().S(fmt.Sprintf(lc.Get("edit.title"), beautifulLink(hyphaName)))
//line views/mutators.qtpl:99
	qw422016.N().S(`</h1>
		`)
//line views/mutators.qtpl:100
	qw422016.N().S(warning)
//line views/mutators.qtpl:100
	qw422016.N().S(`
		<textarea name="text" class="edit-form__textarea" autofocus>`)
//line views/mutators.qtpl:101
	qw422016.E().S(textAreaFill)
//line views/mutators.qtpl:101
	qw422016.N().S(`</textarea>
		<p class="edit-form__message-zone">
        	<input id="text" type="text" name="message" class="edit-form__message" placeholder="`)
//line views/mutators.qtpl:103
	qw422016.E().S(lc.Get("edit.tag"))
//line views/mutators.qtpl:103
	qw422016.N().S(`" aria-label="`)
//line views/mutators.qtpl:103
	qw422016.E().S(lc.Get("edit.tag"))
//line views/mutators.qtpl:103
	qw422016.N().S(`">
        </p>
		<p class="edit-form__buttons">
            <button type="submit" name="action" class="btn btn_accent edit-form__save" value="Save">`)
//line views/mutators.qtpl:106
	qw422016.E().S(lc.Get("edit.save"))
//line views/mutators.qtpl:106
	qw422016.N().S(`</button>
            <button type="submit" name="action" class="btn edit-form__preview" value="Preview">`)
//line views/mutators.qtpl:107
	qw422016.E().S(lc.Get("edit.preview"))
//line views/mutators.qtpl:107
	qw422016.N().S(`</button>
            <a href="/hypha/`)
//line views/mutators.qtpl:108
	qw422016.E().S(hyphaName)
//line views/mutators.qtpl:108
	qw422016.N().S(`" class="btn btn_weak">`)
//line views/mutators.qtpl:108
	qw422016.E().S(lc.Get("ui.cancel"))
//line views/mutators.qtpl:108
	qw422016.N().S(`</a>
        </p>
	</form>
	<p class="warning">`)
//line views/mutators.qtpl:111
	qw422016.E().S(lc.Get("edit.preview_tip"))
//line views/mutators.qtpl:111
	qw422016.N().S(`</p>
	<article class="edit__preview">`)
//line views/mutators.qtpl:112
	qw422016.N().S(renderedPage)
//line views/mutators.qtpl:112
	qw422016.N().S(`</article>
</main>
`)
//line views/mutators.qtpl:114
	qw422016.N().S(Toolbar(user.FromRequest(rq), lc))
//line views/mutators.qtpl:114
	qw422016.N().S(`
`)
//line views/mutators.qtpl:115
	streameditScripts(qw422016)
//line views/mutators.qtpl:115
	qw422016.N().S(`
`)
//line views/mutators.qtpl:116
}

//line views/mutators.qtpl:116
func WritePreview(qq422016 qtio422016.Writer, rq *http.Request, hyphaName, textAreaFill, message, warning string, renderedPage string) {
//line views/mutators.qtpl:116
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/mutators.qtpl:116
	StreamPreview(qw422016, rq, hyphaName, textAreaFill, message, warning, renderedPage)
//line views/mutators.qtpl:116
	qt422016.ReleaseWriter(qw422016)
//line views/mutators.qtpl:116
}

//line views/mutators.qtpl:116
func Preview(rq *http.Request, hyphaName, textAreaFill, message, warning string, renderedPage string) string {
//line views/mutators.qtpl:116
	qb422016 := qt422016.AcquireByteBuffer()
//line views/mutators.qtpl:116
	WritePreview(qb422016, rq, hyphaName, textAreaFill, message, warning, renderedPage)
//line views/mutators.qtpl:116
	qs422016 := string(qb422016.B)
//line views/mutators.qtpl:116
	qt422016.ReleaseByteBuffer(qb422016)
//line views/mutators.qtpl:116
	return qs422016
//line views/mutators.qtpl:116
}

//line views/mutators.qtpl:118
func streameditScripts(qw422016 *qt422016.Writer) {
//line views/mutators.qtpl:118
	qw422016.N().S(`
<script src="/static/editor.js"></script>
`)
//line views/mutators.qtpl:120
	for _, scriptPath := range cfg.EditScripts {
//line views/mutators.qtpl:120
		qw422016.N().S(`
<script src="`)
//line views/mutators.qtpl:121
		qw422016.E().S(scriptPath)
//line views/mutators.qtpl:121
		qw422016.N().S(`"></script>
`)
//line views/mutators.qtpl:122
	}
//line views/mutators.qtpl:122
	qw422016.N().S(`
`)
//line views/mutators.qtpl:123
}

//line views/mutators.qtpl:123
func writeeditScripts(qq422016 qtio422016.Writer) {
//line views/mutators.qtpl:123
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/mutators.qtpl:123
	streameditScripts(qw422016)
//line views/mutators.qtpl:123
	qt422016.ReleaseWriter(qw422016)
//line views/mutators.qtpl:123
}

//line views/mutators.qtpl:123
func editScripts() string {
//line views/mutators.qtpl:123
	qb422016 := qt422016.AcquireByteBuffer()
//line views/mutators.qtpl:123
	writeeditScripts(qb422016)
//line views/mutators.qtpl:123
	qs422016 := string(qb422016.B)
//line views/mutators.qtpl:123
	qt422016.ReleaseByteBuffer(qb422016)
//line views/mutators.qtpl:123
	return qs422016
//line views/mutators.qtpl:123
}
