// Code generated by qtc from "nav.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/nav.qtpl:1
package views

//line views/nav.qtpl:1
import "net/http"

//line views/nav.qtpl:2
import "strings"

//line views/nav.qtpl:3
import "github.com/bouncepaw/mycorrhiza/user"

//line views/nav.qtpl:4
import "github.com/bouncepaw/mycorrhiza/util"

// This is the <nav> seen on top of many pages.

//line views/nav.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/nav.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/nav.qtpl:8
type navEntry struct {
	path  string
	title string
}

var navEntries = []navEntry{
	{"page", "Hypha"},
	{"edit", "Edit"},
	{"history", "History"},
	{"revision", "NOT REACHED"},
	{"rename-ask", "Rename"},
	{"delete-ask", "Delete"},
	{"text", "Raw text"},
}

//line views/nav.qtpl:23
func StreamNavHTML(qw422016 *qt422016.Writer, rq *http.Request, hyphaName, navType string, revisionHash ...string) {
//line views/nav.qtpl:23
	qw422016.N().S(`
`)
//line views/nav.qtpl:25
	u := user.FromRequest(rq)

//line views/nav.qtpl:26
	qw422016.N().S(`
	<nav class="hypha-tabs main-width">
		<ul class="hypha-tabs__flex">
`)
//line views/nav.qtpl:29
	for _, entry := range navEntries {
//line views/nav.qtpl:30
		if navType == "revision" && entry.path == "revision" {
//line views/nav.qtpl:30
			qw422016.N().S(`			<li class="hypha-tabs__tab hypha-tabs__tab_active">
				<span class="hypha-tabs__selection">`)
//line views/nav.qtpl:32
			qw422016.E().S(revisionHash[0])
//line views/nav.qtpl:32
			qw422016.N().S(`</span>
			</li>
`)
//line views/nav.qtpl:34
		} else if navType == entry.path {
//line views/nav.qtpl:34
			qw422016.N().S(`			<li class="hypha-tabs__tab hypha-tabs__tab_active">
				<span class="hypha-tabs__selection">`)
//line views/nav.qtpl:36
			qw422016.E().S(entry.title)
//line views/nav.qtpl:36
			qw422016.N().S(`</span>
			</li>
`)
//line views/nav.qtpl:38
		} else if entry.path != "revision" && u.CanProceed(entry.path) {
//line views/nav.qtpl:38
			qw422016.N().S(`			<li class="hypha-tabs__tab">
				<a class="hypha-tabs__link" href="/`)
//line views/nav.qtpl:40
			qw422016.E().S(entry.path)
//line views/nav.qtpl:40
			qw422016.N().S(`/`)
//line views/nav.qtpl:40
			qw422016.E().S(hyphaName)
//line views/nav.qtpl:40
			qw422016.N().S(`">`)
//line views/nav.qtpl:40
			qw422016.E().S(entry.title)
//line views/nav.qtpl:40
			qw422016.N().S(`</a>
			</li>
`)
//line views/nav.qtpl:42
		}
//line views/nav.qtpl:43
	}
//line views/nav.qtpl:43
	qw422016.N().S(`		</ul>
	</nav>
`)
//line views/nav.qtpl:46
}

//line views/nav.qtpl:46
func WriteNavHTML(qq422016 qtio422016.Writer, rq *http.Request, hyphaName, navType string, revisionHash ...string) {
//line views/nav.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/nav.qtpl:46
	StreamNavHTML(qw422016, rq, hyphaName, navType, revisionHash...)
//line views/nav.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line views/nav.qtpl:46
}

//line views/nav.qtpl:46
func NavHTML(rq *http.Request, hyphaName, navType string, revisionHash ...string) string {
//line views/nav.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line views/nav.qtpl:46
	WriteNavHTML(qb422016, rq, hyphaName, navType, revisionHash...)
//line views/nav.qtpl:46
	qs422016 := string(qb422016.B)
//line views/nav.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line views/nav.qtpl:46
	return qs422016
//line views/nav.qtpl:46
}

//line views/nav.qtpl:48
func StreamUserMenuHTML(qw422016 *qt422016.Writer, u *user.User) {
//line views/nav.qtpl:48
	qw422016.N().S(`
`)
//line views/nav.qtpl:49
	if user.AuthUsed {
//line views/nav.qtpl:49
		qw422016.N().S(`
<li class="header-links__entry header-links__entry_user">
	`)
//line views/nav.qtpl:51
		if u.Group == "anon" {
//line views/nav.qtpl:51
			qw422016.N().S(`
	<a href="/login" class="header-links__link">Login</a>
	`)
//line views/nav.qtpl:53
		} else {
//line views/nav.qtpl:53
			qw422016.N().S(`
	<a href="/page/`)
//line views/nav.qtpl:54
			qw422016.E().S(util.UserHypha)
//line views/nav.qtpl:54
			qw422016.N().S(`/`)
//line views/nav.qtpl:54
			qw422016.E().S(u.Name)
//line views/nav.qtpl:54
			qw422016.N().S(`" class="header-links__link">`)
//line views/nav.qtpl:54
			qw422016.E().S(u.Name)
//line views/nav.qtpl:54
			qw422016.N().S(`</a>
	`)
//line views/nav.qtpl:55
		}
//line views/nav.qtpl:55
		qw422016.N().S(`
</li>
`)
//line views/nav.qtpl:57
	}
//line views/nav.qtpl:57
	qw422016.N().S(`
`)
//line views/nav.qtpl:58
}

//line views/nav.qtpl:58
func WriteUserMenuHTML(qq422016 qtio422016.Writer, u *user.User) {
//line views/nav.qtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/nav.qtpl:58
	StreamUserMenuHTML(qw422016, u)
//line views/nav.qtpl:58
	qt422016.ReleaseWriter(qw422016)
//line views/nav.qtpl:58
}

//line views/nav.qtpl:58
func UserMenuHTML(u *user.User) string {
//line views/nav.qtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
//line views/nav.qtpl:58
	WriteUserMenuHTML(qb422016, u)
//line views/nav.qtpl:58
	qs422016 := string(qb422016.B)
//line views/nav.qtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
//line views/nav.qtpl:58
	return qs422016
//line views/nav.qtpl:58
}

//line views/nav.qtpl:60
func StreamRelativeHyphaeHTML(qw422016 *qt422016.Writer, relatives string) {
//line views/nav.qtpl:60
	qw422016.N().S(`
<aside class="relative-hyphae layout-card">
	<h2 class="relative-hyphae__title layout-card__title">Relative hyphae</h2>
	`)
//line views/nav.qtpl:63
	qw422016.N().S(relatives)
//line views/nav.qtpl:63
	qw422016.N().S(`
</aside>
`)
//line views/nav.qtpl:65
}

//line views/nav.qtpl:65
func WriteRelativeHyphaeHTML(qq422016 qtio422016.Writer, relatives string) {
//line views/nav.qtpl:65
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/nav.qtpl:65
	StreamRelativeHyphaeHTML(qw422016, relatives)
//line views/nav.qtpl:65
	qt422016.ReleaseWriter(qw422016)
//line views/nav.qtpl:65
}

//line views/nav.qtpl:65
func RelativeHyphaeHTML(relatives string) string {
//line views/nav.qtpl:65
	qb422016 := qt422016.AcquireByteBuffer()
//line views/nav.qtpl:65
	WriteRelativeHyphaeHTML(qb422016, relatives)
//line views/nav.qtpl:65
	qs422016 := string(qb422016.B)
//line views/nav.qtpl:65
	qt422016.ReleaseByteBuffer(qb422016)
//line views/nav.qtpl:65
	return qs422016
//line views/nav.qtpl:65
}

//line views/nav.qtpl:67
func StreamSubhyphaeHTML(qw422016 *qt422016.Writer, subhyphae string) {
//line views/nav.qtpl:67
	qw422016.N().S(`
`)
//line views/nav.qtpl:68
	if strings.TrimSpace(subhyphae) != "" {
//line views/nav.qtpl:68
		qw422016.N().S(`
<section class="subhyphae">
	<h2 class="subhyphae__title">Subhyphae</h2>
	<nav class="subhyphae__nav">
		<ul class="subhyphae__list">
		`)
//line views/nav.qtpl:73
		qw422016.N().S(subhyphae)
//line views/nav.qtpl:73
		qw422016.N().S(`
		</ul>
	</nav>
</section>
`)
//line views/nav.qtpl:77
	}
//line views/nav.qtpl:77
	qw422016.N().S(`
`)
//line views/nav.qtpl:78
}

//line views/nav.qtpl:78
func WriteSubhyphaeHTML(qq422016 qtio422016.Writer, subhyphae string) {
//line views/nav.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/nav.qtpl:78
	StreamSubhyphaeHTML(qw422016, subhyphae)
//line views/nav.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line views/nav.qtpl:78
}

//line views/nav.qtpl:78
func SubhyphaeHTML(subhyphae string) string {
//line views/nav.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line views/nav.qtpl:78
	WriteSubhyphaeHTML(qb422016, subhyphae)
//line views/nav.qtpl:78
	qs422016 := string(qb422016.B)
//line views/nav.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line views/nav.qtpl:78
	return qs422016
//line views/nav.qtpl:78
}
