// Code generated by qtc from "readers.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line hypview/readers.qtpl:1
package hypview

//line hypview/readers.qtpl:1
import "net/http"

//line hypview/readers.qtpl:2
import "strings"

//line hypview/readers.qtpl:3
import "path"

//line hypview/readers.qtpl:4
import "os"

//line hypview/readers.qtpl:6
import "github.com/bouncepaw/mycorrhiza/internal/cfg"

//line hypview/readers.qtpl:7
import "github.com/bouncepaw/mycorrhiza/internal/hyphae"

//line hypview/readers.qtpl:8
import "github.com/bouncepaw/mycorrhiza/l18n"

//line hypview/readers.qtpl:9
import "github.com/bouncepaw/mycorrhiza/internal/mimetype"

//line hypview/readers.qtpl:10
import "github.com/bouncepaw/mycorrhiza/internal/user"

//line hypview/readers.qtpl:11
import "github.com/bouncepaw/mycorrhiza/web/viewutil"

//line hypview/readers.qtpl:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line hypview/readers.qtpl:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line hypview/readers.qtpl:13
func StreamMediaMenu(qw422016 *qt422016.Writer, rq *http.Request, h hyphae.Hypha, u *user.User) {
//line hypview/readers.qtpl:13
	qw422016.N().S(`
`)
//line hypview/readers.qtpl:15
	lc := l18n.FromRequest(rq)

//line hypview/readers.qtpl:16
	qw422016.N().S(`
<main class="main-width media-tab">
	<h1>`)
//line hypview/readers.qtpl:18
	qw422016.N().S(lc.Get("ui.media_title", &l18n.Replacements{"name": beautifulLink(h.CanonicalName())}))
//line hypview/readers.qtpl:18
	qw422016.N().S(`</h1>
	`)
//line hypview/readers.qtpl:19
	switch h.(type) {
//line hypview/readers.qtpl:20
	case *hyphae.MediaHypha:
//line hypview/readers.qtpl:20
		qw422016.N().S(`
		<p class="explanation">`)
//line hypview/readers.qtpl:21
		qw422016.E().S(lc.Get("ui.media_tip"))
//line hypview/readers.qtpl:21
		qw422016.N().S(` <a href="/help/en/media" class="shy-link">`)
//line hypview/readers.qtpl:21
		qw422016.E().S(lc.Get("ui.media_what_is"))
//line hypview/readers.qtpl:21
		qw422016.N().S(`</a></p>
	`)
//line hypview/readers.qtpl:22
	default:
//line hypview/readers.qtpl:22
		qw422016.N().S(`
		<p class="explanation">`)
//line hypview/readers.qtpl:23
		qw422016.E().S(lc.Get("ui.media_empty"))
//line hypview/readers.qtpl:23
		qw422016.N().S(` <a href="/help/en/media" class="shy-link">`)
//line hypview/readers.qtpl:23
		qw422016.E().S(lc.Get("ui.media_what_is"))
//line hypview/readers.qtpl:23
		qw422016.N().S(`</a></p>
	`)
//line hypview/readers.qtpl:24
	}
//line hypview/readers.qtpl:24
	qw422016.N().S(`

	<section class="amnt-grid">
	`)
//line hypview/readers.qtpl:27
	switch h := h.(type) {
//line hypview/readers.qtpl:28
	case *hyphae.MediaHypha:
//line hypview/readers.qtpl:28
		qw422016.N().S(`
		`)
//line hypview/readers.qtpl:30
		mime := mimetype.FromExtension(path.Ext(h.MediaFilePath()))
		fileinfo, err := os.Stat(h.MediaFilePath())

//line hypview/readers.qtpl:31
		qw422016.N().S(`
		`)
//line hypview/readers.qtpl:32
		if err == nil {
//line hypview/readers.qtpl:32
			qw422016.N().S(`
		<fieldset class="amnt-menu-block">
			<legend class="modal__title modal__title_small">`)
//line hypview/readers.qtpl:34
			qw422016.E().S(lc.Get("ui.media_stat"))
//line hypview/readers.qtpl:34
			qw422016.N().S(`</legend>
			<p class="modal__confirmation-msg"><b>`)
//line hypview/readers.qtpl:35
			qw422016.E().S(lc.Get("ui.media_stat_size"))
//line hypview/readers.qtpl:35
			qw422016.N().S(`</b> `)
//line hypview/readers.qtpl:35
			qw422016.E().S(lc.GetPlural64("ui.media_size_value", fileinfo.Size()))
//line hypview/readers.qtpl:35
			qw422016.N().S(`</p>
			<p><b>`)
//line hypview/readers.qtpl:36
			qw422016.E().S(lc.Get("ui.media_stat_mime"))
//line hypview/readers.qtpl:36
			qw422016.N().S(`</b> `)
//line hypview/readers.qtpl:36
			qw422016.E().S(mime)
//line hypview/readers.qtpl:36
			qw422016.N().S(`</p>
		</fieldset>
		`)
//line hypview/readers.qtpl:38
		}
//line hypview/readers.qtpl:38
		qw422016.N().S(`

		`)
//line hypview/readers.qtpl:40
		if strings.HasPrefix(mime, "image/") {
//line hypview/readers.qtpl:40
			qw422016.N().S(`
		<fieldset class="amnt-menu-block">
			<legend class="modal__title modal__title_small">`)
//line hypview/readers.qtpl:42
			qw422016.E().S(lc.Get("ui.media_include"))
//line hypview/readers.qtpl:42
			qw422016.N().S(`</legend>
			<p class="modal__confirmation-msg">`)
//line hypview/readers.qtpl:43
			qw422016.E().S(lc.Get("ui.media_include_tip"))
//line hypview/readers.qtpl:43
			qw422016.N().S(`</p>
			<pre class="codeblock"><code>img { `)
//line hypview/readers.qtpl:44
			qw422016.E().S(h.CanonicalName())
//line hypview/readers.qtpl:44
			qw422016.N().S(` }</code></pre>
		</fieldset>
		`)
//line hypview/readers.qtpl:46
		}
//line hypview/readers.qtpl:46
		qw422016.N().S(`
	`)
//line hypview/readers.qtpl:47
	}
//line hypview/readers.qtpl:47
	qw422016.N().S(`

	`)
//line hypview/readers.qtpl:49
	if u.CanProceed("upload-binary") {
//line hypview/readers.qtpl:49
		qw422016.N().S(`
	<form action="/upload-binary/`)
//line hypview/readers.qtpl:50
		qw422016.E().S(h.CanonicalName())
//line hypview/readers.qtpl:50
		qw422016.N().S(`"
			method="post" enctype="multipart/form-data"
			class="upload-binary modal amnt-menu-block">
		<fieldset class="modal__fieldset">
			<legend class="modal__title modal__title_small">`)
//line hypview/readers.qtpl:54
		qw422016.E().S(lc.Get("ui.media_new"))
//line hypview/readers.qtpl:54
		qw422016.N().S(`</legend>
			<p class="modal__confirmation-msg">`)
//line hypview/readers.qtpl:55
		qw422016.E().S(lc.Get("ui.media_new_tip"))
//line hypview/readers.qtpl:55
		qw422016.N().S(`</p>
			<label for="upload-binary__input"></label>
			<input type="file" id="upload-binary__input" name="binary">

			<button type="submit" class="btn stick-to-bottom" value="Upload">`)
//line hypview/readers.qtpl:59
		qw422016.E().S(lc.Get("ui.media_upload"))
//line hypview/readers.qtpl:59
		qw422016.N().S(`</button>
		</fieldset>
	</form>
	`)
//line hypview/readers.qtpl:62
	}
//line hypview/readers.qtpl:62
	qw422016.N().S(`


	`)
//line hypview/readers.qtpl:65
	switch h := h.(type) {
//line hypview/readers.qtpl:66
	case *hyphae.MediaHypha:
//line hypview/readers.qtpl:66
		qw422016.N().S(`
		`)
//line hypview/readers.qtpl:67
		if u.CanProceed("remove-media") {
//line hypview/readers.qtpl:67
			qw422016.N().S(`
		<form action="/remove-media/`)
//line hypview/readers.qtpl:68
			qw422016.E().S(h.CanonicalName())
//line hypview/readers.qtpl:68
			qw422016.N().S(`" method="post" class="modal amnt-menu-block" method="POST">
			<fieldset class="modal__fieldset">
				<legend class="modal__title modal__title_small">`)
//line hypview/readers.qtpl:70
			qw422016.E().S(lc.Get("ui.media_remove"))
//line hypview/readers.qtpl:70
			qw422016.N().S(`</legend>
				<p class="modal__confirmation-msg">`)
//line hypview/readers.qtpl:71
			qw422016.E().S(lc.Get("ui.media_remove_tip"))
//line hypview/readers.qtpl:71
			qw422016.N().S(`</p>
				<button type="submit" class="btn" value="Remove media">`)
//line hypview/readers.qtpl:72
			qw422016.E().S(lc.Get("ui.media_remove_button"))
//line hypview/readers.qtpl:72
			qw422016.N().S(`</button>
			</fieldset>
		</form>
		`)
//line hypview/readers.qtpl:75
		}
//line hypview/readers.qtpl:75
		qw422016.N().S(`
	`)
//line hypview/readers.qtpl:76
	}
//line hypview/readers.qtpl:76
	qw422016.N().S(`

	</section>
</main>
`)
//line hypview/readers.qtpl:80
}

//line hypview/readers.qtpl:80
func WriteMediaMenu(qq422016 qtio422016.Writer, rq *http.Request, h hyphae.Hypha, u *user.User) {
//line hypview/readers.qtpl:80
	qw422016 := qt422016.AcquireWriter(qq422016)
//line hypview/readers.qtpl:80
	StreamMediaMenu(qw422016, rq, h, u)
//line hypview/readers.qtpl:80
	qt422016.ReleaseWriter(qw422016)
//line hypview/readers.qtpl:80
}

//line hypview/readers.qtpl:80
func MediaMenu(rq *http.Request, h hyphae.Hypha, u *user.User) string {
//line hypview/readers.qtpl:80
	qb422016 := qt422016.AcquireByteBuffer()
//line hypview/readers.qtpl:80
	WriteMediaMenu(qb422016, rq, h, u)
//line hypview/readers.qtpl:80
	qs422016 := string(qb422016.B)
//line hypview/readers.qtpl:80
	qt422016.ReleaseByteBuffer(qb422016)
//line hypview/readers.qtpl:80
	return qs422016
//line hypview/readers.qtpl:80
}

//line hypview/readers.qtpl:83
func StreamRevision(qw422016 *qt422016.Writer, meta viewutil.Meta, h hyphae.Hypha, contents, revHash string) {
//line hypview/readers.qtpl:83
	qw422016.N().S(`
<main class="main-width">
	<section>
		<p>`)
//line hypview/readers.qtpl:86
	qw422016.E().S(meta.Lc.Get("ui.revision_warning"))
//line hypview/readers.qtpl:86
	qw422016.N().S(` <a href="/rev-text/`)
//line hypview/readers.qtpl:86
	qw422016.E().S(revHash)
//line hypview/readers.qtpl:86
	qw422016.N().S(`/`)
//line hypview/readers.qtpl:86
	qw422016.E().S(h.CanonicalName())
//line hypview/readers.qtpl:86
	qw422016.N().S(`">`)
//line hypview/readers.qtpl:86
	qw422016.E().S(meta.Lc.Get("ui.revision_link"))
//line hypview/readers.qtpl:86
	qw422016.N().S(`</a></p>
		`)
//line hypview/readers.qtpl:87
	qw422016.N().S(NaviTitle(meta, h.CanonicalName()))
//line hypview/readers.qtpl:87
	qw422016.N().S(`
		`)
//line hypview/readers.qtpl:88
	qw422016.N().S(contents)
//line hypview/readers.qtpl:88
	qw422016.N().S(`
	</section>
</main>
`)
//line hypview/readers.qtpl:91
	for _, scriptPath := range cfg.ViewScripts {
//line hypview/readers.qtpl:91
		qw422016.N().S(`
<script src="`)
//line hypview/readers.qtpl:92
		qw422016.E().S(scriptPath)
//line hypview/readers.qtpl:92
		qw422016.N().S(`"></script>
`)
//line hypview/readers.qtpl:93
	}
//line hypview/readers.qtpl:93
	qw422016.N().S(`
`)
//line hypview/readers.qtpl:94
}

//line hypview/readers.qtpl:94
func WriteRevision(qq422016 qtio422016.Writer, meta viewutil.Meta, h hyphae.Hypha, contents, revHash string) {
//line hypview/readers.qtpl:94
	qw422016 := qt422016.AcquireWriter(qq422016)
//line hypview/readers.qtpl:94
	StreamRevision(qw422016, meta, h, contents, revHash)
//line hypview/readers.qtpl:94
	qt422016.ReleaseWriter(qw422016)
//line hypview/readers.qtpl:94
}

//line hypview/readers.qtpl:94
func Revision(meta viewutil.Meta, h hyphae.Hypha, contents, revHash string) string {
//line hypview/readers.qtpl:94
	qb422016 := qt422016.AcquireByteBuffer()
//line hypview/readers.qtpl:94
	WriteRevision(qb422016, meta, h, contents, revHash)
//line hypview/readers.qtpl:94
	qs422016 := string(qb422016.B)
//line hypview/readers.qtpl:94
	qt422016.ReleaseByteBuffer(qb422016)
//line hypview/readers.qtpl:94
	return qs422016
//line hypview/readers.qtpl:94
}
