// Code generated by qtc from "remove_media.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line hypview/remove_media.qtpl:1
package hypview

//line hypview/remove_media.qtpl:1
import "fmt"

//line hypview/remove_media.qtpl:2
import "net/http"

//line hypview/remove_media.qtpl:3
import "github.com/bouncepaw/mycorrhiza/l18n"

//line hypview/remove_media.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line hypview/remove_media.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line hypview/remove_media.qtpl:5
func StreamRemoveMediaAsk(qw422016 *qt422016.Writer, rq *http.Request, hyphaName string) {
//line hypview/remove_media.qtpl:5
	qw422016.N().S(`
`)
//line hypview/remove_media.qtpl:7
	lc := l18n.FromRequest(rq)

//line hypview/remove_media.qtpl:8
	qw422016.N().S(`
<main class="main-width">
	<form class="modal" action="/remove-media/`)
//line hypview/remove_media.qtpl:10
	qw422016.E().S(hyphaName)
//line hypview/remove_media.qtpl:10
	qw422016.N().S(`" method="post">
		<fieldset class="modal__fieldset">
			<legend class="modal__title">
				`)
//line hypview/remove_media.qtpl:13
	qw422016.N().S(fmt.Sprintf(lc.Get("ui.ask_remove_media"), beautifulLink(hyphaName)))
//line hypview/remove_media.qtpl:13
	qw422016.N().S(`
			</legend>
			<p class="modal__confirmation-msg">
				`)
//line hypview/remove_media.qtpl:16
	qw422016.N().S(lc.Get("ui.ask_really", &l18n.Replacements{"verb": lc.Get("ui.ask_remove_media_verb"), "name": fmt.Sprintf("<em>%s</em>", hyphaName)}))
//line hypview/remove_media.qtpl:16
	qw422016.N().S(`
			</p>
			<button type="submit" value="Confirm" class="btn" autofocus>
				`)
//line hypview/remove_media.qtpl:19
	qw422016.E().S(lc.Get("ui.confirm"))
//line hypview/remove_media.qtpl:19
	qw422016.N().S(`
			</button>
			<a href="/hypha/`)
//line hypview/remove_media.qtpl:21
	qw422016.E().S(hyphaName)
//line hypview/remove_media.qtpl:21
	qw422016.N().S(`" class="btn btn_weak">
				`)
//line hypview/remove_media.qtpl:22
	qw422016.E().S(lc.Get("ui.cancel"))
//line hypview/remove_media.qtpl:22
	qw422016.N().S(`
			</a>
		</fieldset>
	</form>
</main>
`)
//line hypview/remove_media.qtpl:27
}

//line hypview/remove_media.qtpl:27
func WriteRemoveMediaAsk(qq422016 qtio422016.Writer, rq *http.Request, hyphaName string) {
//line hypview/remove_media.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line hypview/remove_media.qtpl:27
	StreamRemoveMediaAsk(qw422016, rq, hyphaName)
//line hypview/remove_media.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line hypview/remove_media.qtpl:27
}

//line hypview/remove_media.qtpl:27
func RemoveMediaAsk(rq *http.Request, hyphaName string) string {
//line hypview/remove_media.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line hypview/remove_media.qtpl:27
	WriteRemoveMediaAsk(qb422016, rq, hyphaName)
//line hypview/remove_media.qtpl:27
	qs422016 := string(qb422016.B)
//line hypview/remove_media.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line hypview/remove_media.qtpl:27
	return qs422016
//line hypview/remove_media.qtpl:27
}
