// Code generated by qtc from "recent_changes.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/recent_changes.qtpl:1
package templates

//line templates/recent_changes.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/recent_changes.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/recent_changes.qtpl:1
func StreamRecentChangesHTML(qw422016 *qt422016.Writer, changes []string, n int) {
//line templates/recent_changes.qtpl:1
	qw422016.N().S(`
<div class="layout">
<main class="main-width recent-changes">
	<h1>Recent Changes</h1>
	<p><a href="/">← Back</a></p>

	<nav class="recent-changes__count">
		See 
	`)
//line templates/recent_changes.qtpl:9
	for _, m := range []int{20, 0, 50, 0, 100} {
//line templates/recent_changes.qtpl:9
		qw422016.N().S(`
	`)
//line templates/recent_changes.qtpl:10
		switch m {
//line templates/recent_changes.qtpl:11
		case 0:
//line templates/recent_changes.qtpl:11
			qw422016.N().S(`
		<span aria-hidden="true">|</span>
		`)
//line templates/recent_changes.qtpl:13
		case n:
//line templates/recent_changes.qtpl:13
			qw422016.N().S(`
		<b>`)
//line templates/recent_changes.qtpl:14
			qw422016.N().D(n)
//line templates/recent_changes.qtpl:14
			qw422016.N().S(`</b>
		`)
//line templates/recent_changes.qtpl:15
		default:
//line templates/recent_changes.qtpl:15
			qw422016.N().S(`
		<a href="/recent-changes/`)
//line templates/recent_changes.qtpl:16
			qw422016.N().D(m)
//line templates/recent_changes.qtpl:16
			qw422016.N().S(`">`)
//line templates/recent_changes.qtpl:16
			qw422016.N().D(m)
//line templates/recent_changes.qtpl:16
			qw422016.N().S(`</a>
	`)
//line templates/recent_changes.qtpl:17
		}
//line templates/recent_changes.qtpl:17
		qw422016.N().S(`
	`)
//line templates/recent_changes.qtpl:18
	}
//line templates/recent_changes.qtpl:18
	qw422016.N().S(`
		recent changes
	</nav>

	<p><img class="icon" width="20" height="20" src="https://upload.wikimedia.org/wikipedia/commons/4/46/Generic_Feed-icon.svg">Subscribe via <a href="/recent-changes-rss">RSS</a>, <a href="/recent-changes-atom">Atom</a> or <a href="/recent-changes-json">JSON feed</a>.</p>

	`)
//line templates/recent_changes.qtpl:29
	qw422016.N().S(`

	<section class="recent-changes__list" role="feed">
	`)
//line templates/recent_changes.qtpl:32
	if len(changes) == 0 {
//line templates/recent_changes.qtpl:32
		qw422016.N().S(`
		<p>Could not find any recent changes.</p>
	`)
//line templates/recent_changes.qtpl:34
	} else {
//line templates/recent_changes.qtpl:34
		qw422016.N().S(`
		`)
//line templates/recent_changes.qtpl:35
		for i, entry := range changes {
//line templates/recent_changes.qtpl:35
			qw422016.N().S(`
		<ul class="recent-changes__entry rc-entry" role="article"
		    aria-setsize="`)
//line templates/recent_changes.qtpl:37
			qw422016.N().D(n)
//line templates/recent_changes.qtpl:37
			qw422016.N().S(`" aria-posinset="`)
//line templates/recent_changes.qtpl:37
			qw422016.N().D(i)
//line templates/recent_changes.qtpl:37
			qw422016.N().S(`">
			 `)
//line templates/recent_changes.qtpl:38
			qw422016.N().S(entry)
//line templates/recent_changes.qtpl:38
			qw422016.N().S(`
		</ul>
		`)
//line templates/recent_changes.qtpl:40
		}
//line templates/recent_changes.qtpl:40
		qw422016.N().S(`
	`)
//line templates/recent_changes.qtpl:41
	}
//line templates/recent_changes.qtpl:41
	qw422016.N().S(`
	</section>
</main>
</div>
`)
//line templates/recent_changes.qtpl:45
}

//line templates/recent_changes.qtpl:45
func WriteRecentChangesHTML(qq422016 qtio422016.Writer, changes []string, n int) {
//line templates/recent_changes.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/recent_changes.qtpl:45
	StreamRecentChangesHTML(qw422016, changes, n)
//line templates/recent_changes.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line templates/recent_changes.qtpl:45
}

//line templates/recent_changes.qtpl:45
func RecentChangesHTML(changes []string, n int) string {
//line templates/recent_changes.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/recent_changes.qtpl:45
	WriteRecentChangesHTML(qb422016, changes, n)
//line templates/recent_changes.qtpl:45
	qs422016 := string(qb422016.B)
//line templates/recent_changes.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/recent_changes.qtpl:45
	return qs422016
//line templates/recent_changes.qtpl:45
}
